[project]
name = "lab6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi>=0.123.0",
    "jupyter>=1.1.1",
    "streamlit==1.51.0",
    "uvicorn>=0.38.0",
]
